### ISSUE TITLE
Initiales Eingabefenster

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/Slice2Volume#10]
Wie gestern im Telemeeting besprochen, wird Robert zuerst einmal eine Dialogbox programmieren.
Ich erstelle trotzdem nochmal ein Issue, falls Fragen oder Diskussionsbedarf aufkommen. Außerdem können wir es dann abhaken und später die Fortschritte des Projekts besser nachvollziehen :-)

Wunsch:
- Auswählen der jeweiligen Pfade statt manuelle Eingabe in den Code
- Angabe, wo der erste Histologieschnitt im CT liegt 
Entweder als Nummer oder etwas benutzerfreundlicher:
> How much of the sample was removed before cutting? --> [Eingabe] µm
Achtung: Die Probe schrumpft auf ungefähr 69% des Ausgansvolumens. 100 µm in der Probe entsprechen somit ~150 µm im CT. Mit diesem Umrechnungsfaktor haben wir bisher gearbeitet und das passt erfahrungsgemäß auch ganz gut.

**Comment by jo-mueller** [comment]
Top of my head, das dialogfenster sollte enthalten:

- Pfad zu elastix.exe
- Pfad zu transformix
- Pfad zu Ordner mit volumetrischer Maske (binäres CT)
- Pfad zu Ordner mit Histo-basiertem Input

- Pixel-spacing CT (default: 100µm)
- Histo-spacing (default 150µm)
- "omitted distance": Wie weit vom ende des Organs wurde geschnitten?
- Schnittachse der histo-bilder: (axial/sagittal/coronal)

**Comment by jo-mueller** [comment]
@Nuklearfish: Ich hab jetzt mal alle aktuellen Änderungen in den dev/master branch zusammengeführt. Das Eingabefenster fehlt mir aber noch - kannst du das vielleicht noch in den /dev branch reinpacken so wie du's eigentlich schon gemacht hast?

Vor allem die Browse funktion bei den Pfadnamen ist glaube ich seh hilfreich. Ich hab immer wieder Bugs mit / und \ Zeichen, das sollte eigentlich nicht mehr auftreten wenn der Filebrowser die Pfade ausspuckt.

**Comment by jo-mueller** [comment]
Solved.
