### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by schneidorlein** [jo-mueller/Slice2Volume#12]
show a progress bar during the registration

**Comment by schneidorlein** [comment]
now one can see a progress bar when the actual registration (which means when elastix is starting) begins. that elastix registration takes most of the time and thats why the progress bar starts there and not right from the beginning because the first steps (e.g. the creation of the dapimask) is rather fast. and also it would be really complicated to create a progress bar right from the beginning :D

**Comment by Theresa-S** [comment]
Sieht gut aus :-)

**Comment by jo-mueller** [comment]
General: When you push commits, please be more specific as to what exactly you changed - makes it a bit difficult to see which branch adresses which issue:
![screenshot](https://user-images.githubusercontent.com/38459088/82823717-61291c80-9ea8-11ea-8607-e30d74221b2c.PNG)

**Comment by schneidorlein** [comment]
unter den jeweiligen issues steht immer #nummer und diese nummer steht dann hinter issue ;)
also zB: exception handling #2 -> issue 2

**Comment by jo-mueller** [comment]
Jep, ich weiß schon. Ich muss mich dann beim merging der branches trotzdem immer durch die issues klicken um zu schauen welcher commit was macht, oder ich gehe die Änderungen händisch durch - ist auch bisschen aufwendig. 
Wenn bei den commits einfach in noch in zwei-drei Punkten stünde was der macht würde ich mich etwas leichter tun dabei den Überblick zu behalten.

**Comment by jo-mueller** [comment]
Noch ein kleiner Nachtrag dazu: Ich hab das Gefühl dass der Progress bar (der sehr schön ist, gute Arbeit!) den Progress von schicht 0 bis schicht 350 anzeigt. Verarbeitet werden ja aber eigentlich nur rund 30 Bilder oder sowas. 
Vielleicht kann man schon vorm eröffnen des PB die Anzahl der zu registrierenden Histo-bilder ermitteln und dann übergeben? Dann weiß der PB genauer bei wieviel % er gerade ist.

**Comment by jo-mueller** [comment]
Made major changes to the script - but I think the progress bar is a bit off now. Can someone (@schneidorlein ? O:) ) maybe look into this?
