### ISSUE TITLE
2. Alphatest --> crash bei results.mhd

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/Slice2Volume#13]
Hallo, 
ich habe jetzt nochmal getestet und zwei Anmerkungen plus ein neues Issue. Hier das Issue

Das Programm gibt eine Fehlermeldung bei 8.2 % Progress auf:
![grafik](https://user-images.githubusercontent.com/61883896/82795043-b6970680-9e73-11ea-9344-f2a161a99696.png)

Die Datei wird im Skript nicht angelegt, sondern nur aufgerufen --> .mhd erscheint auch nur einmal im Code. Das Problem ist vermutlich itk related, fehlt mir noch eine Input Datei?

**Comment by jo-mueller** [comment]
Ich würde hier noch einen ähnlichen Bug anmerken: Ich hab das Gefühl dass irgendwelche Produkte der Registrierung (zB. results.mhd, oder TransformParameters.0.txt) bei mehrmaligen Ausführen des Skripts nicht korrekt überschrieben werden und dann beim transformieren Ärger machen.

@schneidorlein: Vielleicht wäre es hier hilfreich einfach bei jeder Ausführung des Skripts einen frischen (leeren) Ordner zu erstellen? Der Ordner der jetzt "trafo" heißt würde dann halt output0, output1,... heißen und wäre dann garantiert leer, so dass Relikte aus vorherigen Registrierungen keine Rolle mehr spielen sollten.

**Comment by jo-mueller** [comment]
Solved: New folder created for every script execution.
