### ISSUE TITLE
Allen Brain Atlas

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/Slice2Volume#15]
Zu der Verfügbarkeit des Allen Mouse Brain Atlas gibt es folgenden Forumsbeitrag:
https://community.brain-map.org/t/mouse-brain-volume/105

Die nrrd Dateien sind dann hier zu finden:
http://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/annotation/ccf_2017/

Der nächste Schritt ist, zu testen ob man das nrrd statt des CT Volumens für die Registrierung verwenden kann. Ich versuche es sobald wie möglich zu testen, wenn wer eher Zeit und Lust hat, viel Spaß :-)

**Comment by Theresa-S** [comment]
Hier die Annotiationen dazu sind hier (hoffentlich):
http://api.brain-map.org/api/v2/structure_graph_download/1.xml

**Comment by jo-mueller** [comment]
Ich hab's jetzt eigentlich ganz solide hinbekommen :)
Also zumindest die registrierung von ratio-maps auf die Atlas-Maske. 
Als nächstes müsste man mal ein Python-Script schreiben dass atlas-regionen und histo-readout in eine Tabelle packt.

**Comment by Theresa-S** [comment]
Läuft bei mir nicht so ganz... Ich fange wegen der Orientierung nochmal ein neues Issue an :-)

**Comment by Theresa-S** [comment]
Alternativer Atlas (verwendet von DZNE Kooperationspartnern):
https://wiki.mouseimaging.ca/display/MICePub/Mouse+Brain+Atlases
http://repo.mouseimaging.ca/repo/DSURQE_40micron_nifti/

**Comment by jo-mueller** [comment]
works with Atlas now :) you can even add/remove specific areas from the Atlas!
