### ISSUE TITLE
Volumentric Data - MRT

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/Slice2Volume#16]
Am Ende wollen wir die 2D Daten nicht nur aufs CT registrieren, sondern auf ein beliebiges 3D Volumen --> CT, MRT oder Brain Atlas. Beim Testlauf mit einem konturierten MRT Volumen hat bei mir auch die Registrierung nicht geklappt.

Beim MRT gibt es das Problem, dass die Voxel nicht immer isotrop sind, d.h. die Voxel können unterschiedliche Kantenlängen haben, vor allem in z Richtung. Wie lösen wir das Problem am elegantesten? Könnte man die Infos aus den Metadaten holen?

Ich kann dazu gerne mehrere MRTs (raw, kontruiert, gefiltert) und die Histo einer Maus per SyncTrayzor schicken.

**Comment by jo-mueller** [comment]
Ich glaube das Problem würde ich eher außerhalb von Slice2Volume lösen. Um das anzugehen müsste man das MRT auf den Atlas registrieren (oder umgekehrt), und dafür ist Slice2Volume eigentlich nicht gemacht. Dafür wäre eine 3D->3D registrierung nötig, also Elastix oder Big Warp.
Kann ich den Thread hier schließen?
