### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by jo-mueller** [jo-mueller/Slice2Volume#2]
There are some unhandled exceptions:
- If the paths the user has to specify do not end with "/", the script crashes without hint at the reason.

**Comment by schneidorlein** [comment]
i fixed this issue. now one does NOT need to end the root with "\\" for example it looks like this:

root = "C:\\Users\\Acer\\Documents\\oncoray\\daten_theresa";
coronal_brain = "Brain.nrrd";
root2 = "C:\\test";

is that better? it should be more intuitive right?

**Comment by schneidorlein** [comment]
i mean of course like this (with the double backslash in between):

root = "C:\\Users\\Acer\\Documents\\oncoray\\daten_theresa";
coronal_brain = "Brain.nrrd";
root2 = "C:\\test";

**Comment by schneidorlein** [comment]
it seems like that one can not enter a doublebackslash here, it always converts it into a simple onebackslash.
so in between there is still a doublebackslash, but not at the end of the root!
that one has to put a doublebackslash in between, one can mention in the readme i suppose

**Comment by jo-mueller** [comment]
Well. As soon as Robert has finished the input GUI, the filebrowser functions always return folders with a "/" at the end and files without it. I would close this issue because it should be covered by Robert's task.
