### ISSUE TITLE
Namenskürzel + Versionsnummern

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/Slice2Volume#7]
Liebe alle,

wenn wir zu viert an dem Thema arbeiten, brauchen wir ein System, um den Überblick zu behalten. Ich würde vorschlagen, dass jeder Code im dev-branch mit den jeweiligen Kürzel der Bearbeiter (TS, RG, JM, MS) und eine Versionsnummer erhält.
Bei Versionsnummern finde ich persönlich das Datum (JJJJ-MM-DD) immer ganz praktisch, ich bin aber offen für weitere Vorschläge.

Was denkt ihr?

LG

**Comment by jo-mueller** [comment]
Hm...da bin ich dagegen. Github ist ja dazu da dass man den Kram (Versionsnummer, Kürzel, etc) gerade nicht mehr braucht, sondern genau verfolgen kann wer wann welche Änderung am Skript gemacht hat (und alle Versionen rekonstruieren kann wenn nötig). Wer möchte kann sich ja einen extra-branch erstellen (zusätzlich zu master & dev) und seine Änderungen dann zunächst zu dev hinzufügen. 
Wenn alle von uns die Änderungen dann approved haben, kann man sie dann zum master-branch zufügen.
