### ISSUE TITLE
Error handling - get top slice

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/Slice2Volume#8]
Könntet ihr hier ein weiteres **if** einfügen (oder **else**? Ich bin mir bei der Syntax nicht sicher) bei dem abgefangen wird, dass in jedem Bild eine 0 steht? Z.B. Ich hab die Fehlermeldung zuerst nicht verstanden, sowas wie eine Nachricht "Überall ist 0 drin, deine Daten sind doof/ weiter oben ist ein Problem"

Tipp: waitForUser()

![Error messages_1](https://user-images.githubusercontent.com/61883896/79198682-2ad19980-7e34-11ea-933b-63d2ada43aa6.png)

**Comment by Theresa-S** [comment]
![grafik](https://user-images.githubusercontent.com/61883896/84118797-c85fd880-aa33-11ea-9a81-5e9b27681fb5.png)

--> works in principle 
But: perhaps we have to change the text. The problem here was that the folder gH2AX did not exist, because I called it differently:
dir_gH2AX = root + "\\NeuN\\"

![grafik](https://user-images.githubusercontent.com/61883896/84119061-268cbb80-aa34-11ea-94bd-d7c31051116c.png)



![grafik](https://user-images.githubusercontent.com/61883896/84118899-e9c0c480-aa33-11ea-99f8-34329379f947.png)

**Comment by Theresa-S** [comment]
Suggestion for text:

"Oops. An error occurred. Possible reasons are: 
- CT and/ or DAPI image data is empty/ completely black. 
- Given directory of image data does not exit (check for typos:-)
- ... [was auch immer noch so auftaucht]"

**Comment by jo-mueller** [comment]
Das Problem mit den Filenamen und der "/" und "\\" Problematik sollte eigentlich durch Robert's GUI abgedeckt werden - die formatiert das automatisch. Ich schliess das Issue mal.
